import {FileBlob, SpreadsheetFile} from '@oai/artifact-tool';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const [file,mode,analysis]=process.argv.slice(2);
const wb=await SpreadsheetFile.importXlsx(await FileBlob.load(file));
const errors=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#NUM!|#NULL!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:300},maxChars:2000});
const script=fileURLToPath(new URL('./verify_workbook_package.py',import.meta.url));
const result=JSON.parse(execFileSync(process.env.WJX_PYTHON_PATH||'python3',[script,file,...(analysis?[analysis]:[])],{encoding:'utf8'}));
result.formula_scan=errors.ndjson;
process.stdout.write(JSON.stringify(result,null,2));
if(!result.passed)process.exitCode=1;
